name: DPBoss Auto Result Checker

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Auto Bot
        env:
          ONESIGNAL_KEY: ${{ secrets.ONESIGNAL_KEY }}
        run: node bot.js
